### ISSUE TITLE
The parameters of the "get_cmdlog" API?

### ISSUE THREAD

**Issue by yclin1209** [pynvme/pynvme#100]
Thanks for your excellent work on pynvme, 
It is very helpful for me to develop SSD test program.

I made some changes on cmdlog, but I can't call get_cmdlog correctly.
Always get errors such as "invalid parameter". 
How can I transfer its parameter correctly?
e.g.: result = jsonrpc_call(sock, 'get_cmdlog','???') 

Thank You. 
Regards

**Comment by cranechu** [comment]
Thanks for using pynvme!
The jsonrpc call "get_cmdlog" has only one parameter, and has to be integer value of a valid queue id. e.g.: 
```python
qpair = ...
result = jsonrpc_call(sock, 'get_cmdlog', qpair.sqid)
```

**Comment by yclin1209** [comment]
Thank you for your quick reply.
I insert the code snippet to test_examples.py:test_jsonrpc_list_qpairs(),
but the jsonrpc_call(sock, 'get_cmdlog', q1.sqid) still got error: "invalid request" .
I also try integer: 0~2, but  still got "invalid request".
Am I missing anything else necessary? 

 `q1 = d.Qpair(nvme0, 8)
    result = jsonrpc_call(sock, 'get_cmdlog', q1.sqid)`

**Comment by cranechu** [comment]
please refer to this piece of script:
``` python
    q1 = d.Qpair(nvme0, 8)
    result = jsonrpc_call(sock, 'list_all_qpair')
    assert len(result) == 2
    assert result[0]['qid']-1 == 0
    assert result[1]['qid']-1 == 1
    cmdlog = jsonrpc_call(sock, 'get_cmdlog', [result[0]['qpair']])
    for c in cmdlog:
        logging.info(c)
    cmdlog = jsonrpc_call(sock, 'get_cmdlog', [result[1]['qpair']])
    assert cmdlog == []
```

Our vscode extension is also built on top of these jsonrpc calls. 

Thanks, 
-Crane

**Comment by yclin1209** [comment]
> please refer to this piece of script:
> 
> ```python
>     q1 = d.Qpair(nvme0, 8)
>     result = jsonrpc_call(sock, 'list_all_qpair')
>     assert len(result) == 2
>     assert result[0]['qid']-1 == 0
>     assert result[1]['qid']-1 == 1
>     cmdlog = jsonrpc_call(sock, 'get_cmdlog', [result[0]['qpair']])
>     for c in cmdlog:
>         logging.info(c)
>     cmdlog = jsonrpc_call(sock, 'get_cmdlog', [result[1]['qpair']])
>     assert cmdlog == []
> ```
> 
> Our vscode extension is also built on top of these jsonrpc calls.

   It's works!
   Thanks for your help.
