### ISSUE TITLE
Strange Qpair behavior

### ISSUE THREAD

**Issue by ebrittain** [pynvme/pynvme#103]
setfeatures commands to feature ID 9 are failing with status 00/02 unless the qpair fixture is used from conftest.py:

Passing without warnings:
```python
def test_a(nvme0, qpair):
    iv = 1
    num_of_entry = (nvme0.cap & 0xffff) + 1
    num_of_entry = min(1024, num_of_entry)
    qpair = d.Qpair(nvme0, num_of_entry, iv=iv)

    nvme0.setfeatures(9, cdw11=iv).waitdone()
    nvme0.getfeatures(9, cdw11=iv).waitdone()
```

Warning thrown when setfeatures is sent:
```python
def test_b(nvme0):
    iv = 1
    num_of_entry = (nvme0.cap & 0xffff) + 1
    num_of_entry = min(1024, num_of_entry)
    qpair = d.Qpair(nvme0, num_of_entry, iv=iv)

    nvme0.setfeatures(9, cdw11=iv).waitdone()
    nvme0.getfeatures(9, cdw11=iv).waitdone()
```

I'm not doing anything differently in the two cases except using the qpair fixutre.

**Comment by cranechu** [comment]
the status 00/02 (Invalid Field in Command) is returned by the DUT, so please check with the device provider why it returns the error status.
