### ISSUE TITLE
Secondary process non exist error during controller reset after power cycle 

### ISSUE THREAD

**Issue by Kalathieswari** [pynvme/pynvme#106]
ERROR : 
python3: nvme_ctrlr.c:3221: spdk_nvme_secondary_process_nonexist: Assertion `ref > 0' failed.
Fatal Python error: Aborted

Scenario:
Multiple controllers are up in the setup. We are issuing power cycle. After that trying to issue controller reset to all controllers in the system during that seeing the above error for few controllers.
What can be the cause of this error?

**Comment by cranechu** [comment]
Please share us with the full log file, and the scripts to reproduce if possible. Thanks!
