### ISSUE TITLE
Supporting MSI mode

### ISSUE THREAD

**Issue by williszheng** [pynvme/pynvme#111]
Hi:
Does pynvme support MSI interrupt mode ？ 
From /src/intr_mgt.c we found that: 
void intc_init(struct spdk_nvme_ctrlr *ctrlr)
{
  bool ret;
  
  // interrupt is enabled on PCIe devices only
  assert(ctrlr->trid.trtype == SPDK_NVME_TRANSPORT_PCIE);

  //search msix first, if the operation fail, will switch to msi intr
  ret = msix_intc_init(ctrlr, &ctrlr->pynvme_intc_ctrl);
  if (ret == false)
  {
    ret = msi_intc_init(ctrlr, &ctrlr->pynvme_intc_ctrl);
  }

  assert(ret == true);  // controller must support at least one kind of interrupt
}

Does THE msi_intc_init function be work normally ？

Waiting for your answer and appreciate your help

**Comment by cranechu** [comment]
Hi, pynvme supports both MSIx and MSI.

**Comment by williszheng** [comment]
Is there any tip about how to enable it ?  :v

**Comment by cranechu** [comment]
If the DUT does not support MSIx, but supports MSI, MSI will be enabled automatically.

**Comment by OUZYcn** [comment]
https://pynvme.readthedocs.io/en/latest/intro.html

please update document. 
![image](https://user-images.githubusercontent.com/47710598/173320374-664d7e04-aff7-4f38-88b2-74e62a92b612.png)
