### ISSUE TITLE
problem with pylance in vscode

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#119]
hello
How are you doing? 
I can not use it for mass testing at work, but it works well for individual failure analysis
I recently changed the language server in vscode from jedi to pylance
However, pylance doesn't recognize the classes in the nvme.so module, have you ever seen such a symptom?
Thank you

**Comment by cranechu** [comment]
Hi, long time no see. 
We are fully transferred to our commercial product **PyNVMe3**: https://pynv.me/3/. It works well with latest vscode, which should use pylance as default language server. Please use that one. Thanks!
