### ISSUE TITLE
Qpair function problem at cc.en transition

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#32]
Hi

Sorry~ i have too many question

i tested qpair create / delete(del qpair)  => CC.EN transition (1->0->1)

but seems like qpair function still remaining in memory

qpair create (qpair=d.Qpair(nvme0,xx)) command to run SQ1,CQ1 create -> SQ1,CQ1 delete -> SQ1,CQ1 Create at 2nd loop

3rd loop more duplicate. SQ1,CQ1 create -> SQ1,CQ1 delete -> SQ1,CQ1 create -> SQ1,CQ1 delete -> SQ1,CQ1 create -> SQ1,CQ1 delete 

but insted of using cc.en transition. use reset function no this issue.

**Comment by cranechu** [comment]
Hi, Catogts, 

Could you please share with me a minimized piece of script to reproduce these issues? 

Thanks, 
-Crane

**Comment by catogts** [comment]
Hi, Crane
minimized script is below

for a in range(100):
 qpair=q.Qpair(nvme0,16)
 buf=d.Buffer(512)
 nvme0n1.write(qpair,buf,0,1).waitdone()
 del qlist
 del buf
 nvme0[0x14]=int('00460000',16)
 time.sleep(2)
 nvme0[0x14]=int('00460001',16)
 time.sleep(2)

result is starting  qpair create/delete SQ1,CQ1  * loop at test start and fail about 5~6 loops

i checked this problem at test device throught UART

reset is no problem. only issue at  cc.en toggle

**Comment by catogts** [comment]
ok~ right
I couldn't use the tab key because I wrote a portable device
qlist => qpair 
miss typing

**Comment by cranechu** [comment]
OK, so here is your script:

``` python
def test_issue_32(nvme0, nvme0n1):
    for a in range(100):
        qpair=d.Qpair(nvme0, 16)
        buf=d.Buffer(512)
        nvme0n1.write(qpair,buf,0,1).waitdone()
        del qpair
        del buf
        nvme0[0x14]=int('00460000',16)
        time.sleep(2)
        nvme0[0x14]=int('00460001',16)
        time.sleep(2)    
```

In the above script, it resets NVMe controller by writing NVMe registers. However, pynvme host driver does not understand that the controller is resetted, and so its internal data and state are different from that in the device. For example, after CC.EN 1=>0=>1, the admin qpair head/tail pointers are different in host driver and NVMe device. 

In order to reset both host driver and NVMe device, we suggest to use Controller.reset() method. For example: 
``` python
def test_issue_32(nvme0, nvme0n1):
    for a in range(100):
        qpair=d.Qpair(nvme0, 16)
        buf=d.Buffer(512)
        nvme0n1.write(qpair,buf,0,1).waitdone()
        del qpair
        del buf
        nvme0.reset()
```
I think you have already tested this one, right? 

Thanks, 
-Crane

**Comment by catogts** [comment]
I tested with register backup(include aqs,acq tail,header) before cc.en transition and restore register after cc.en 1
How can i initialize host driver without reset?

**Comment by cranechu** [comment]
We do not support to initialize host driver without reset.

**Comment by cranechu** [comment]
We will consider this reset flow in our next phase of development.

**Comment by catogts** [comment]
Thank you!
