### ISSUE TITLE
Subsystem Reset issue ERROR nvme_ctrlr.c

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#35]
Hi crane

I tested pynvme at 2 platform (1 desktop, 1 server)

but both system can not operate subsystem reset

pynvme occur error below
--desktop log--
ERROR nvme_ctrlr.c(728) nvme_ctrlr_shutdown: get_csys() failed
python3: nvme_ctrl.c:728: nvme_ctrlr_shutdown: Assertion 'false' failed
--server log--
INFO Driver.c(498) probe_cb: Attaching to NVMe Controller at 0000:xx:xx.x
ERROR nvme_pcie.c(488) nvme_pcie_ctrlr_map_cmb: get registers failed
python3: nvme_pcie.c:488: nvme_pcie_ctrlr_map_cmb: Assertion 'false' failed.

any sample can not subsystem reset.

i use master brance

**Comment by cranechu** [comment]
From NVMe Spec: 

> 10.5 Controller Fatal Status Condition
> 
> Performing an NVM Subsystem Reset (NSSR) may cause PCI Express links to go down as part of resetting the NVM subsystem. Host software may have undesirable effects related to PCI Express links going down (e.g., some host operating systems or hypervisors may crash). 

What you observed is just because PCIe links down.

**Comment by cranechu** [comment]
We also fill confuse about this operation. Some drives fail as the same link down issue, but some drives do pass. Need more investigation.

**Comment by catogts** [comment]
Thank you
i will try more sample and system
availble pcie link setup in driver level?

**Comment by cranechu** [comment]
> availble pcie link setup in driver level?

You can try Pcie.reset()
