### ISSUE TITLE
issue about ioworker close in multi iowoker

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#36]
Hi crane

i use multi iowoker for extreme stress

but somtimes some ioworker can not close. (detailed no going next step. seems like halt)

All Iowoker process ended  at debug process window but not process close ioworker.

i see UserWarning aboit semaphore_tracker in process debug console in vscode

Are there any additional points I should consider to manage iowokers?

sorry too many question ^^;

**Comment by cranechu** [comment]
We have an example of stress test which starts multiple ioworkers: https://github.com/cranechu/pynvme/blob/master/scripts/stress/endurance_test.py

Try this script in your test platform, and see if any special difference with your script. 
Please also upload scripts and logs for more details. 

Thanks, 
-Crane
