### ISSUE TITLE
How can use backgorund operation?

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#39]
Hi crane

I test some workload with trim(background)

I used Process function in multiprocessing module

But not work  correctly. 
(Maybe not working correctly multiprocess module)
 How can i use background operation(ex. Python function)  except ioworker?

Thank you

**Comment by cranechu** [comment]
Hi, Catogts, 

Please refer to this script: 
https://github.com/pynvme/pynvme/blob/b221104794c7a87f4c4354e3c4997b8f4c0e9ee9/scripts/test_examples.py#L41

Thanks, 
-Crane

**Comment by catogts** [comment]
Thank you~
