### ISSUE TITLE
Suggest controller reset option

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#52]
Hi crane

I read spdk 19.10 release note

Spdk 19.10 support "no shutdown notification reset" 

Could you support this feature in pynvme option?

Thank you

**Comment by cranechu** [comment]
Good idea. Thanks for the suggestion! 
We are considering to set option _no_shn_notification_ to true by default, and only send shutdown notification in test scripts when it is required by this API call: 
``` python
Subsystem.shutdown_notify(abrupt=False)
```
Can this meet your needs? 

Thanks, 
-Crane

**Comment by catogts** [comment]
ok thankyou crane!
