### ISSUE TITLE
SGL

### ISSUE THREAD

**Issue by danmcleran** [pynvme/pynvme#55]
Any plans to support SGLs?

**Comment by cranechu** [comment]
No for now, because we don't have drives supporting SGL. But if you have any specific requirement, we can talk about the collaboration in detail. Thanks!

**Comment by danmcleran** [comment]
Sorry I did not respond. I am looking into how we can collaborate on adding SGL support in the future.

**Comment by cranechu** [comment]
Sure. Warmly welcome!
