### ISSUE TITLE
issue about zns test

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#67]
hi crane

i tested zns extension use qemu zns emulation driver

but not correctly work on zns driver

could you tell me which environment you tested?

**Comment by cranechu** [comment]
Hi, Catogts, 

It is developed for a business customer. It is still in the early stage and I cannot talk too much about it. 
However, I will try to make it work with qemu in future. Do you have any requirements on ZNS test? 

Thanks, 
-Crane
