### ISSUE TITLE
how can i get cmd.status?

### ISSUE THREAD

**Issue by catogts** [pynvme/pynvme#79]
Hi crane

I know how to check pass/fail for expected status using pytest.warn  

But is there a way to check this in the test script when an unwanted status (Userwarning) returns?

For example, you may need to use status check or status return values ​​for cmds that are not supported.

thank you!

**Comment by cranechu** [comment]
You can try this callback with only one parameter cpl. In the callback, we can check the whole completion entry data structure in the script.  

```python
    def cb2(cpl):
        logging.info(cpl)
        assert cpl[0] == 0
        assert cpl[1] == 0
        assert len(cpl) == 4
        assert type(cpl) is tuple
    nvme0n1.read(qpair, buf, 0, cb=cb2).waitdone()
```
