### ISSUE TITLE
nvme init timeout when test ZNS SSD

### ISSUE THREAD

**Issue by qwbouc** [pynvme/pynvme#83]
test env:
PC,  fedora31, ZNS SSD

----------
test script as bellow:

def test_zns1(nvme0):

    buf = Buffer()

    cple = None
    def cb_cpl(cpl):
        nonlocal cple;cple=cpl

    nvme0.send_cmd(0x79, buf, cdw10=0, cdw12=406, cdw13=0,cb=cb_cpl).waitdone()
    logging.info("cple:{}".format(cple))

-------------
result:
-------------------------------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------------------------------
[2020-11-18 14:54:47.457] INFO script(60): setup random seed: 0x164976f5
ERROR
------------------------------------------------------------------------------------------------------------- live log teardown -------------------------------------------------------------------------------------------------------------
[2020-11-18 14:55:17.592] INFO script(62): test duration: 30.135 sec

================================================================================================================== ERRORS ===================================================================================================================
________________________________________________________________________________________________________ ERROR at setup of test_zns1 ________________________________________________________________________________________________________

pcie = <nvme.Pcie object at 0x7faf3a9172f0>

    @pytest.fixture(scope="function")
    def nvme0(pcie):
>       ret = d.Controller(pcie)

conftest.py:79:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
driver_wrap.pyx:887: in nvme.Controller.__cinit__
    ???
driver_wrap.pyx:927: in nvme.Controller._nvme_init
    ???
driver_wrap.pyx:1145: in nvme.Controller.waitdone
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TimeoutError: pynvme timeout in driver

driver_wrap.pyx:93: TimeoutError
------------------------------------------------------------------------------------------------------------ Captured log setup -------------------------------------------------------------------------------------------------------------
INFO     root:conftest.py:60 setup random seed: 0x164976f5
============================================================================================================= warnings summary ==============================================================================================================
qwb_test.py::test_zns1
  /home/pynvme/conftest.py:79: UserWarning: drive timeout: qpair: 0, cid: 126
    ret = d.Controller(pcie)

qwb_test.py::test_zns1
  /home/pynvme/conftest.py:79: UserWarning: ERROR status: 07/ff
    ret = d.Controller(pcie)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================================== short test summary info ==========================================================================================================
ERROR qwb_test.py::test_zns1 - TimeoutError: pynvme timeout in driver

------
source code:

nvme.Controller._nvme_init

            # 7. identify controller and all namespaces
            nvme0.identify(Buffer(4096)).waitdone()

                nvme0.identify(Buffer(4096)).waitdone()

            nvme0.setfeatures(0x7, cdw11=0xfffefffe).waitdone()
            cdw0 = nvme0.getfeatures(0x7).waitdone()

question: 
1.how to find which waitdone function cause the problem?
2.Whether pynvme adapt to ZNS SSD?

**Comment by yfwayne** [comment]
ZNS is supported.

You can try the zone specific command test_zns_management_receive in test_zns.py. Please note by default zns test is skipped, so you need to turn on the test by change skip_zns = False
