### ISSUE TITLE
conformance removed?

### ISSUE THREAD

**Issue by dpdingtaoqb** [pynvme/pynvme#92]
new here. why remove conformance? recently developing nvme emulator. conformance maybe a way to test the function. reading from your wiki. it seems that conformance covers all the test of function such as admin and io request?

**Comment by cranechu** [comment]
We don't have enough resource to maintain it in an open source project.

**Comment by dpdingtaoqb** [comment]
> We don't have enough resource to maintain it in an open source project.

what a pity,  i thought conformance maybe a good way to decrease difficulty of learning.
anyway, thank for your jobs

**Comment by cranechu** [comment]
file:///home/cranechu/Downloads/conformance-master.zip

Here is the last snapshot of the conformance scripts.
