### ISSUE TITLE
Help ubuntu OS version

### ISSUE THREAD

**Issue by seulayoon123** [pynvme/pynvme#95]
Hi I am seula
I will Test Pynvme
But An error occurs in progress
My ubuntu OS version is 20.10
Is pynvme available this version?
Thanks you
Have a good day😀

**Comment by cranechu** [comment]
Hi, Seula, 

Welcome to use pynvme. We support most of the popular Linux distributions, and including Ubuntu 20.10 of course. 
If you have got any error, please paste the log here. 

Thanks, 
-Crane
