### ISSUE TITLE
Controller(Pcie('01:00.0')) failing

### ISSUE THREAD

**Issue by pratdandamudi** [pynvme/pynvme#96]
Hello, 

I'm trying to initialize test NVMe controller but the initialization times out

Below is the error message:
------------------------------------------------------------------------------------------------
<console>:1: UserWarning: drive timeout: qpair: 0, cid: 126
<console>:1: UserWarning: ERROR status: 07/ff
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "driver_wrap.pyx", line 906, in nvme.Controller.__cinit__
  File "driver_wrap.pyx", line 946, in nvme.Controller._nvme_init
  File "driver_wrap.pyx", line 1160, in nvme.Controller.waitdone
  File "driver_wrap.pyx", line 93, in nvme._timeout_signal_handler
TimeoutError: pynvme timeout in driver

--------------------------------------------------------------------------------------------------

The boot drive for my linux PC is also a NVMe drive. Does this have anything to do with the error?

Thanks,
Prathyusha

**Comment by cranechu** [comment]
Could you please give us a full log generated by:

```shell
make setup
make test TESTS="driver_test.py::test_ioworker_iops_multiple_queue[1]"
```

**Comment by pratdandamudi** [comment]
controller on 04:00.0 is the NVMe boot drive

**Comment by cranechu** [comment]
So, try this command line to specify BDF in the test:

```shell
make setup
make test TESTS="driver_test.py::test_ioworker_iops_multiple_queue[1]" pciaddr=0000:01:00.0
```

**Comment by pratdandamudi** [comment]
Thanks for your suggestion

I specified the BDF in the test and below is the output: Got timeout error

make test TESTS="driver_test.py::test_ioworker_iops_multiple_queue[1]" pciaddr=0000:01:00.0
rm test_0000:01:00.0.log
make pytest 2>test_0000:01:00.0.log | tee -a test_0000:01:00.0.log
make[1]: Entering directory '/home/prathyusha/pynvme'
sudo ./src/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1215 /   1215

NVMe devices
BDF		Vendor	Device	NUMA	Driver		Device name
0000:01:00.0	1b4b	1325	0	uio_pci_generic		-
0000:04:00.0	144d	a808	0	nvme			nvme1

I/OAT DMA
BDF		Vendor	Device	NUMA	Driver

virtio
BDF		Vendor	Device	NUMA	Driver		Device name
VMD
BDF		Numa Node	Driver Name
sudo cat /proc/meminfo
MemTotal:        6075636 kB
MemFree:         1076976 kB
MemAvailable:    1939536 kB
Buffers:           59984 kB
Cached:           985632 kB
SwapCached:            0 kB
Active:          1274128 kB
Inactive:         782420 kB
Active(anon):    1012968 kB
Inactive(anon):    21440 kB
Active(file):     261160 kB
Inactive(file):   760980 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      19530748 kB
SwapFree:       19530748 kB
Dirty:              1044 kB
Writeback:           148 kB
AnonPages:       1010940 kB
Mapped:           447432 kB
Shmem:             23484 kB
KReclaimable:     103192 kB
Slab:             237708 kB
SReclaimable:     103192 kB
SUnreclaim:       134516 kB
KernelStack:       13120 kB
PageTables:        17920 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    21324404 kB
Committed_AS:    5180148 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       37592 kB
VmallocChunk:          0 kB
Percpu:            28800 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:    1215
HugePages_Free:     1215
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         2488320 kB
DirectMap4k:      346136 kB
DirectMap2M:     4825088 kB
DirectMap1G:     2097152 kB
sudo cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 24
model name	: AMD Ryzen 3 3200G with Radeon Vega Graphics
stepping	: 1
microcode	: 0x8108102
cpu MHz		: 2974.891
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7186.14
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 24
model name	: AMD Ryzen 3 3200G with Radeon Vega Graphics
stepping	: 1
microcode	: 0x8108102
cpu MHz		: 1563.823
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7186.14
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 24
model name	: AMD Ryzen 3 3200G with Radeon Vega Graphics
stepping	: 1
microcode	: 0x8108102
cpu MHz		: 3877.347
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7186.14
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 24
model name	: AMD Ryzen 3 3200G with Radeon Vega Graphics
stepping	: 1
microcode	: 0x8108102
cpu MHz		: 1613.300
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7186.14
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

sudo cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
sudo lspci -s 0000:01:00.0 -vv
01:00.0 Non-Volatile memory controller: Marvell Technology Group Ltd. Device 1325 (prog-if 02 [NVM Express])
	Subsystem: Marvell Technology Group Ltd. Device 1325
	Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort+ <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 33
	NUMA node: 0
	Region 0: Memory at f0610000 (64-bit, non-prefetchable) [size=16K]
	Region 4: Memory at f0400000 (64-bit, non-prefetchable) [size=2M]
	Expansion ROM at f0600000 [virtual] [disabled] [size=64K]
	Capabilities: [40] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
		Address: 0000000000000000  Data: 0000
		Masking: 00000000  Pending: 00000000
	Capabilities: [70] Express (v2) Endpoint, MSI 00
		DevCap:	MaxPayload 512 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
			ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 0.000W
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop- FLReset-
			MaxPayload 512 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr+ NonFatalErr- FatalErr- UnsupReq+ AuxPwr- TransPend-
		LnkCap:	Port #0, Speed 16GT/s, Width x4, ASPM not supported
			ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes Disabled- CommClk-
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
		LnkSta:	Speed 8GT/s (downgraded), Width x4 (ok)
			TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Range ABCD, TimeoutDis+, NROPrPrP-, LTR+
			 10BitTagComp+, 10BitTagReq-, OBFF Not Supported, ExtFmt-, EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS+, TPHComp-, ExtTPHComp-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
			 AtomicOpsCtl: ReqEn-
		LnkCtl2: Target Link Speed: 16GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance De-emphasis: -6dB
		LnkSta2: Current De-emphasis Level: -3.5dB, EqualizationComplete+, EqualizationPhase1+
			 EqualizationPhase2+, EqualizationPhase3+, LinkEqualizationRequest-
	Capabilities: [b0] MSI-X: Enable- Count=132 Masked-
		Vector table: BAR=0 offset=00002000
		PBA: BAR=0 offset=00003000
	Capabilities: [d0] Vital Product Data
		Not readable
	Capabilities: [100 v2] Advanced Error Reporting
		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
		UEMsk:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
		UESvrt:	DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr-
		CEMsk:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+
		AERCap:	First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
			MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
		HeaderLog: 00000000 00000000 00000000 00000000
	Capabilities: [148 v1] Device Serial Number 00-00-00-00-00-00-00-00
	Capabilities: [158 v1] Power Budgeting <?>
	Capabilities: [168 v1] Alternative Routing-ID Interpretation (ARI)
		ARICap:	MFVC- ACS-, Next Function: 0
		ARICtl:	MFVC- ACS-, Function Group: 0
	Capabilities: [178 v1] Secondary PCI Express
		LnkCtl3: LnkEquIntrruptEn-, PerformEqu-
		LaneErrStat: 0
	Capabilities: [198 v1] Physical Layer 16.0 GT/s <?>
	Capabilities: [1bc v1] Lane Margining at the Receiver <?>
	Capabilities: [1d4 v1] Single Root I/O Virtualization (SR-IOV)
		IOVCap:	Migration-, Interrupt Message Number: 000
		IOVCtl:	Enable- Migration- Interrupt- MSE- ARIHierarchy+
		IOVSta:	Migration-
		Initial VFs: 16, Total VFs: 16, Number of VFs: 0, Function Dependency Link: 00
		VF offset: 1, stride: 1, Device ID: 1325
		Supported Page Size: 00000553, System Page Size: 00000001
		Region 0: Memory at 00000000f0614000 (64-bit, non-prefetchable)
		VF Migration: offset: 00000000, BIR: 0
	Capabilities: [224 v1] Latency Tolerance Reporting
		Max snoop latency: 0ns
		Max no snoop latency: 0ns
	Capabilities: [22c v1] L1 PM Substates
		L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
			  PortCommonModeRestoreTime=10us PortTPowerOnTime=10us
		L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
			   T_CommonMode=0us LTR1.2_Threshold=0ns
		L1SubCtl2: T_PwrOn=10us
	Capabilities: [23c v1] Dynamic Power Allocation <?>
	Capabilities: [26c v1] LN Requester <?>
	Capabilities: [274 v1] Vendor Specific Information: ID=0002 Rev=4 Len=100 <?>
	Capabilities: [374 v1] Vendor Specific Information: ID=0001 Rev=1 Len=038 <?>
	Capabilities: [3ac v1] Data Link Feature <?>
	Kernel driver in use: uio_pci_generic
	Kernel modules: nvme

ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 6c:4b:90:e5:60:c8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.13/24 brd 192.168.0.255 scope global dynamic noprefixroute enp2s0
       valid_lft 3535sec preferred_lft 3535sec
    inet6 2601:646:8e01:6250:18c6:df38:54f8:e47/64 scope global temporary dynamic 
       valid_lft 3599sec preferred_lft 3599sec
    inet6 2601:646:8e01:6250:421c:253c:ee4e:2c55/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 3599sec preferred_lft 3599sec
    inet6 fe80::b1ff:e0b5:67a6:c22/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether e4:aa:ea:d5:78:2f brd ff:ff:ff:ff:ff:ff
df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             2975688        0   2975688   0% /dev
tmpfs             607564     1860    605704   1% /run
/dev/nvme1n1p5  23899984 10368292  12294600  46% /
tmpfs            3037816        0   3037816   0% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
tmpfs            3037816        0   3037816   0% /sys/fs/cgroup
/dev/loop1         56832    56832         0 100% /snap/core18/1944
/dev/loop2        100224   100224         0 100% /snap/core/10444
/dev/loop3        100352   100352         0 100% /snap/core/10583
/dev/loop4        223232   223232         0 100% /snap/gnome-3-34-1804/60
/dev/loop6         63616    63616         0 100% /snap/gtk-common-themes/1506
/dev/loop0        149632   149632         0 100% /snap/code/50
/dev/loop5        224256   224256         0 100% /snap/gnome-3-34-1804/66
/dev/loop7         52352    52352         0 100% /snap/snap-store/498
/dev/loop9         66432    66432         0 100% /snap/gtk-common-themes/1514
/dev/loop8         56704    56704         0 100% /snap/core18/1932
/dev/loop10        31872    31872         0 100% /snap/snapd/10707
/dev/loop11       147328   147328         0 100% /snap/code/52
/dev/loop12        31744    31744         0 100% /snap/snapd/9721
/dev/loop13        52352    52352         0 100% /snap/snap-store/518
/dev/nvme1n1p7  77170412 25125208  48082068  35% /home
/dev/nvme1n1p1    262144    37328    224816  15% /boot/efi
tmpfs             607560       28    607532   1% /run/user/1000
whoami
prathyusha
groups
prathyusha adm cdrom sudo dip plugdev lpadmin lxd sambashare
lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:01.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:01.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus A
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus B
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 61)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 7
01:00.0 Non-Volatile memory controller: Marvell Technology Group Ltd. Device 1325
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
03:00.0 Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Picasso (rev c9)
05:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Raven/Raven2/Fenghuang HDMI/DP Audio Controller
05:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
05:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
05:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
05:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor
05:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
06:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 61)
date
Thu 21 Jan 2021 06:41:25 PM PST
pwd
/home/prathyusha/pynvme
git status -sb
## HEAD (no branch)
 M .vscode/settings.json
 M Makefile
?? exmples_pynvme_mvl.py
?? report.xls
git --no-pager log -1
commit a5e1c6c7dc083f31866ef2b8e0ea2046daf2366b
Author: Crane Chu <cranechu@gmail.com>
Date:   Thu Jan 7 04:29:44 2021 +0800

    shrink pypi package
sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=0000:01:00.0 -s -v -r Efsx --excelreport=report.xls --verbose
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/prathyusha/pynvme, configfile: pytest.ini
plugins: cov-2.11.1, excel-1.4.2
collecting ... collected 1 item

driver_test.py::test_ioworker_iops_multiple_queue[1] 
-------------------------------- live log setup --------------------------------
[2021-01-21 18:41:26.659] INFO script(60): setup random seed: 0x1fef101a
ERROR
------------------------------ live log teardown -------------------------------
[2021-01-21 18:41:56.698] INFO script(62): test duration: 30.039 sec


==================================== ERRORS ====================================
____________ ERROR at setup of test_ioworker_iops_multiple_queue[1] ____________

pcie = <nvme.Pcie object at 0x7f364cfe52f0>

    @pytest.fixture(scope="function")
    def nvme0(pcie):
>       ret = d.Controller(pcie)

conftest.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
driver_wrap.pyx:906: in nvme.Controller.__cinit__
    ???
driver_wrap.pyx:946: in nvme.Controller._nvme_init
    ???
driver_wrap.pyx:1160: in nvme.Controller.waitdone
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TimeoutError: pynvme timeout in driver

driver_wrap.pyx:93: TimeoutError
------------------------------ Captured log setup ------------------------------
INFO     root:conftest.py:60 setup random seed: 0x1fef101a
=============================== warnings summary ===============================
driver_test.py::test_ioworker_iops_multiple_queue[1]
  /home/prathyusha/pynvme/conftest.py:79: UserWarning: drive timeout: qpair: 0, cid: 126
    ret = d.Controller(pcie)

driver_test.py::test_ioworker_iops_multiple_queue[1]
  /home/prathyusha/pynvme/conftest.py:79: UserWarning: ERROR status: 07/ff
    ret = d.Controller(pcie)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
--------------------------- excel report: report.xls ---------------------------
=========================== short test summary info ============================
ERROR driver_test.py::test_ioworker_iops_multiple_queue[1] - TimeoutError: py...
======================== 2 warnings, 1 error in 30.32s =========================
make[1]: Leaving directory '/home/prathyusha/pynvme'
sudo rm -rf .pytest_cache

**Comment by cranechu** [comment]
Can you try another drive from different vendor? 
From the log, it seems a drive issue.
